name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    - Name=client1_Name
    - Surname=client1_Surname
    - DNI=client1_DNI
    - Birthdate=2000-10-01
    - Number=1231
    - CLI_LOG_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=2
    - Name=client2_Name
    - Surname=client2_Surname
    - DNI=client2_DNI
    - Birthdate=2000-10-02
    - Number=1232
    - CLI_LOG_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=3
    - Name=client3_Name
    - Surname=client3_Surname
    - DNI=client3_DNI
    - Birthdate=2000-10-03
    - Number=1233
    - CLI_LOG_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
version: '3.9'
